### ISSUE TITLE
LoRA sometimes applied twice for first gen at startup

### ISSUE THREAD

**Issue by space-nuko** [kohya-ss/sd-webui-additional-networks#106]
I'm noticing this sometimes if I restart webui after making a gen with additional_networks, sometimes the LoRA weights get applied twice unless the enable checkbox is toggled on/off. Then the problem goes away from the rest of the session. Might have to do with VRAM not being zeroed out at startup?

**Comment by space-nuko** [comment]
Here is an example of the overapplication, versus what the output should normally look like:

![14803-2026999714-1girl, macro lens, full body, solo, masterpiece, 1girl, brown eyes, pink hair, multiple braids, long hair, crosswalk, brown back](https://user-images.githubusercontent.com/24979496/218506398-351eb6db-605b-43b9-9be7-631ccf17db37.png)
![14815-2026999714-1girl, macro lens, full body, solo, masterpiece, 1girl, brown eyes, pink hair, multiple braids, long hair, crosswalk, brown back](https://user-images.githubusercontent.com/24979496/218506394-642a1222-4275-4c32-9c18-67ba4e1dedef.png)

**Comment by kohya-ss** [comment]
Thank you reporting! 

The extension removes the currently applied networks from U-Net and Text Encoder and then add the new networks to them when the network settings are changed.

When I restart the Web UI, the Web UI seems to re-create the instance of the extension.
Therefore, the extension does not know which network is currently applied after restarting, and adds the new network without removing the previous networks.

To resolve the issue, the restart event should be handled by the extension, but I think perhaps the Web UI does not have such an event-hook.

So, it may be required to remove all possible networks when the extension is launched, or when the network settings are changed. I will update as soon as I have time.

As a workaround, to disable Additional Network (check off) and generating an image will remove current networks (if LoRA is applied to both U-Net and Text Encoder), and the overapplication will be cleared.

**Comment by space-nuko** [comment]
> To resolve the issue, the restart event should be handled by the extension, but I think perhaps the Web UI does not have such an event-hook.

I think it does have it actually, it's called `on_script_unloaded`, it's run when the UI restarts internally

**Comment by kohya-ss** [comment]
Thank you for the PR! The issue is seemed to be solved.

**Comment by space-nuko** [comment]
Just realized, you might want to test this for `img2img` also since the PR only looks for the `txt2img` instance of the script, perhaps also check if networks are loaded in the opposite script before applying/restoring them

**Comment by kohya-ss** [comment]
Thank you for the comment. I've tested on following cases with enabling networks on both ``img2img`` and ``txt2img``:
1. generate in ``img2img`` and restart UI
2. generate in  ``txt2img`` and restart UI

The networks seem to be removed in both cases. 

I think because ``restore_networks`` removes all existing networks from U-Net/Text Encoder, so if the networks are loaded in another tab, the networks will be removed anyway.
