### ISSUE TITLE
I don't see any of my Lora

### ISSUE THREAD

**Issue by 616659** [kohya-ss/sd-webui-additional-networks#114]
I followed the tutorial, but then got stuck on "refresh models to select the lora for network module 1"

I have some .safetensors Lora placed inside lora folder, yet i don't think it is detecting any of it. I am using google colab, maybe that's the issue? The Lora correctly shows up on txt2img ui, after clicking "show extra networks" and under Lora tab.

**Comment by xhhdd** [comment]
I also appeared in this situation, using the [https://github.com/AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui)
refreshed many times but couldn't find my lora, when I was sure I had placed the file in the right place

**Comment by xhhdd** [comment]
Oh, I've solved the problem, it was because the file path was wrong, you need to copy the lora file you stored before to
`extensions/sd-webui-additional-networks/models/lora`，`models/Lora` Not the right path

**Comment by zsmhub** [comment]
> Oh, I've solved the problem, it was because the file path was wrong, you need to copy the lora file you stored before to `extensions/sd-webui-additional-networks/models/lora`，`models/Lora` Not the right path

I have the same problem, I can't solve it with your method

**Comment by kohya-ss** [comment]
Sorry for confusing with case-sensitive issue, because I'm tested with Windows env. I fixed it a while ago, so I think there is no problem if you install the extension for clean environment.

**Comment by Guillaume-Georges** [comment]
I had the same problem, couldn't localize the file in .safetensor format. Instead I changed it into .pt format and it worked.
