### ISSUE TITLE
Some LoRAs do not work! (shedding big tears!!!)

### ISSUE THREAD

**Issue by zundamon075** [kohya-ss/sd-webui-additional-networks#119]
When I load and use lora, I get this error and it does not work properly

Error running process_batch: /notebooks/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 395, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 205, in process_batch
    du_state_dict = load_file(model_path)
  File "/usr/local/lib/python3.9/dist-packages/safetensors/torch.py", line 100, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: self.size(-1) must be divisible by 2 to view Byte as Half (different element sizes), but got 148729

**Comment by zundamon075** [comment]
I get this error when I try to load Lora from the ex function!

OS used: Paperspace (linux & ubuntu20.04?)

What should have happened?
It should run as normal and Lora should function

Commit where the problem happens
python: 3.9.13  •  torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.16.2  •  commit: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/076d624a297532d6e4abebe5807fd7c7504d7a73  •  checkpoint: cac0c0b5a7

What platforms do you use to access the UI ?
Linux

What browsers do you use to access the UI ?
Google Chrome

Command Line Arguments
--share --gradio-debug --xformers --enable-insecure-extension-access --no-half

List of extensions
Generate-TransparentIMG
sd-dynamic-prompts
sd-webui-controlnet
sd-webui-lora-block-weight
stable-diffusion-webui-model-toolkit
sd-webui-additional-networks

**Comment by zundamon075** [comment]
Console logs

Error running process_batch: /notebooks/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 395, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 205, in process_batch
    du_state_dict = load_file(model_path)
  File "/usr/local/lib/python3.9/dist-packages/safetensors/torch.py", line 100, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: self.size(-1) must be divisible by 2 to view Byte as Half (different element sizes), but got 148729

**Comment by kohya-ss** [comment]
The file seems to have something wrong. It doesn't seem to be a valid ``.safetensors`` file (or it may be corrupted). Please check the file is a LoRA model trained with sd-scripts. 

If you manually rename ``.pt`` or ``.ckpt`` to ``.safetensors``, it will not work.

**Comment by zundamon075** [comment]
I experimented, and the files were corrupted or not uploading properly!
Sorry for the disturbance (I was very ignorant).
