### ISSUE TITLE
LORA model does not load correctly due to _IncompatibleKeys

### ISSUE THREAD

**Issue by SwannSchilling** [kohya-ss/sd-webui-additional-networks#133]
LoRA model LuisapNijijourney_v1(b33dc6051f5b) loaded: _IncompatibleKeys(missing_keys=['lora_te_wrapped_transformer_text_model_encoder_layers_0_self_attn_k_proj.alpha', "... and 263 alphas. The model doesn't have alpha, use dim (rannk) as alpha. You can ignore this message."], unexpected_keys=[])

**Comment by kohya-ss** [comment]
Hi, the older model (without `alpha`) causes this message. However the extension can handle the model properly, so you can ignore this message.

**Comment by SwannSchilling** [comment]
Thanks for the info! 😊
