### ISSUE TITLE
cannot save metadata

### ISSUE THREAD

**Issue by qdooooo** [kohya-ss/sd-webui-additional-networks#150]
python: 3.10.10  •  torch: 2.0.0+cu118  •  xformers: 0.0.17rc482  •  gradio: 3.23.0  • 

occured after i update to torch2.0 or update the webui .i closed all other extention but this issue did not be solved. 

F12:  component-3799" disabled="

![QQ截图20230328234430](https://user-images.githubusercontent.com/126337827/228293494-969269c3-8fa2-4d59-bec6-857190eb9dcb.png)

**Comment by kohya-ss** [comment]
I think this appears to be a degradation of Gradio. 

@space-nuko 
`interactive` option with gr.Button doesn't seem to work. Sorry to bother you, do you have any idea about this?

**Comment by space-nuko** [comment]
It's because recent Gradio makes `interactive` work for `gr.Button` where it was a no-op before (https://github.com/gradio-app/gradio/pull/3266). This code should be updated so it includes the button in changing `interactive`

https://github.com/kohya-ss/sd-webui-additional-networks/blob/59a72abc3144c2fd08e17481ae65dec5cf441cd6/scripts/metadata_editor.py#L465-L473

**Comment by kohya-ss** [comment]
Thank you for the quick response! If so, would the following change be sufficient? This code seems to be working.

```
  def update_editing(enabled):
    """
    Enable/disable components based on "Editing Enabled" status
    """
    updates = [gr.Textbox.update(interactive=enabled)] * 6
    updates.append(gr.Image.update(interactive=enabled))
    updates.append(gr.Slider.update(interactive=enabled))
    updates.append(gr.Button.update(interactive=enabled))
    return updates
  editing_enabled.change(fn=update_editing, inputs=[editing_enabled], outputs=[display_name, author, source, keywords, description, tags, cover_image, rating, save_metadata_button])
```

**Comment by space-nuko** [comment]
Yes that should work

**Comment by kohya-ss** [comment]
Thanks! I will update now :)
