### ISSUE TITLE
Can`t work while hires fix and Extra args both enabled

### ISSUE THREAD

**Issue by Season02** [kohya-ss/sd-webui-additional-networks#155]
Bug report

If use a mask image and Hires. fix enabled, this error would promopt:
  File "...\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 110, in forward
    return self.org_forward(x) + lx * self.multiplier * self.scale * self.mask
RuntimeError: The size of tensor a (128) must match the size of tensor b (64) at non-singleton dimension 3

**This error will be generated if Extra args and Hires. fix are used at the same time**

**Comment by pxjhll** [comment]
+1
