### ISSUE TITLE
module file conflict

### ISSUE THREAD

**Issue by vladmandic** [kohya-ss/sd-webui-additional-networks#162]
i've been fumbling around this, but i cant find solution.
problem is if two different extensions have exactly the same internal folders/files.

for example, both controlnet and kohya additional networks perform same import
```python
from scripts import xyz_grid_support
```

those are different files that are local to each extension. but python loader in its wisdom decides that module is already loaded so what ends up is that whatever extension loads second will try to use module from first loaded extension - and that will of course fail.

i'm really out of ideas.

i'd love to solve this in core, but for the moment easy solution would be to have both extensions have unique module names - can you do that?

anyone with ideas?

link to issue <https://github.com/vladmandic/automatic/issues/297>

**Comment by kohya-ss** [comment]
Thank you for reporting for this. I agree that renaming the module is an easy solution. I will modify today when I have time.

Just as a side note, I think the reason for the name conflict with `xyz_grid_support` is that ControlNet extension was initially implemented in the form of a modification of this extension😅

**Comment by kohya-ss** [comment]
I've changed the module name. If you have any issue, please let me know.

**Comment by vladmandic** [comment]
both you and cn author jumped on this and fixed it - thank you!
