### ISSUE TITLE
[Bug] can't set value in xyz plot

### ISSUE THREAD

**Issue by FerryHuang** [kohya-ss/sd-webui-additional-networks#168]
In XYZ plot, can't set value for AddNet Model and report error "Expecting value: line 1 column 1 (char 0)"
<img width="949" alt="image" src="https://user-images.githubusercontent.com/71176040/235905943-999c56e3-12bd-435c-9f54-f658b77c0b69.png">
<img width="354" alt="image" src="https://user-images.githubusercontent.com/71176040/235905990-61f54dc8-7f9d-4638-99ff-fe355ab7f2b9.png">

**Comment by FerryHuang** [comment]
Plus, I'm using the latest version webui

**Comment by WooseTheMoose** [comment]
Same Issue.

ValueError: [ValueError('dictionary update sequence element #0 has length 17; 2 is required'), TypeError('vars() argument must have __dict__ attribute')]

**Comment by kohya-ss** [comment]
The latest update might solve the issue. Please update and try again :)

**Comment by FerryHuang** [comment]
> The latest update might solve the issue. Please update and try again :)

It works fine! Great thanks!
