### ISSUE TITLE
[Bug]: Models in "Additional Networks" tab not loaded

### ISSUE THREAD

**Issue by Woisek** [kohya-ss/sd-webui-additional-networks#169]
Since some time now, the LoRAs under "Model" drop down aren't loaded when in the "Additional Networks" tab. So it's not possible to work with them in this tab.
But all LoRAs are working when prompting and generating images. They are visible and available in the overview and they are available in the "Additional Networks" drop down under img2txt and img2im.
I use vlads repo, and also in https://github.com/anapnoe/stable-diffusion-webui-ux it's not working.
But I see that in A1111 it's working, so I'm not quite sure who's gonna have to fix it. But 2 out of 3 not working sets the blame on the extension I guess. 🙂
So, any chance to get this looked up, please?

**Comment by bestcarly** [comment]
I encountered a similar problem. The background output is as follows, but lora does not appear in the drop-down list
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]

**Comment by kohya-ss** [comment]
I've confirmed the bug in Auto1111's web ui in latest version. Details seem to differ somewhat.

When `Additional Network` tab is opened, the model is displayed, but None is displayed twice.

![image](https://user-images.githubusercontent.com/52813779/236664604-e4981179-1baa-4c8c-a29f-a747ca5b896b.png)

After reloading the model with 🔄, the dropdown cannot be opened.

![image](https://user-images.githubusercontent.com/52813779/236664672-f9c8f7d4-bba5-47ca-83be-6186c2f7c503.png)

The models are loaded correctly according to the console output.
```
[AddNet] Updating model hashes...
100%|███████████████████████████████████████████████████████████████████████████████| 74/74 [00:00<00:00, 37007.09it/s]
[AddNet] Updating model hashes...
100%|███████████████████████████████████████████████████████████████████████████████| 74/74 [00:00<00:00, 15003.55it/s]
```

I will investigate further.

@space-nuko Sorry to bother you, if you have any suggestions, I would be happy to hear from you.

**Comment by space-nuko** [comment]
Maybe check when the scanning is happening because it happens on importing the python source at top level and instead use one of the script hooks

**Comment by PowerfulShell** [comment]
same here

**Comment by kohya-ss** [comment]
I think this will be solved in the latest version. If there is any problem, please reopen.

**Comment by Loganavter** [comment]
> I encountered a similar problem. The background output is as follows, but lora does not appear in the drop-down list [AddNet] Updating model hashes... 0it [00:00, ?it/s] [AddNet] Updating model hashes... 0it [00:00, ?it/s] [AddNet] Updating model hashes... 0it [00:00, ?it/s]

I have exactly the same problem as you
```
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
```
The latest version of the extension and stable diffusion. I tried to add a path through the settings, but it didn't help either.

**Comment by Loganavter** [comment]
> I think this will be solved in the latest version. If there is any problem, please reopen.

Can you reopen this thread?

**Comment by LiminalCrew** [comment]
Also getting this problem and I just installed the latest version. 
Can this be reopened or is there a fix?
