### ISSUE TITLE
No longer able to select "None" in X/Y plot for AddNet Model

### ISSUE THREAD

**Issue by amarney4862** [kohya-ss/sd-webui-additional-networks#170]
As of a some update last week, I am no longer able to select "None" in X/Y plot for AddNet Model. The new feature of one-click adding from a dropdown is great, but selecting "None" helps a lot in testing to see if it's actually working, or how. Please bring this back!

**Comment by kohya-ss** [comment]
I didn't change the dropdown, so I think this is caused by the updating of the web ui... I will try to fix it.

**Comment by kohya-ss** [comment]
`None` is added to the list. If there is any problem, please reopen.

**Comment by amarney4862** [comment]
"None" shows up and works properly if you use the button to load all loras in the folder, but you can't type it in or select it from the dropdown.

**Comment by kohya-ss** [comment]
It seems to be working on my end.

![image](https://user-images.githubusercontent.com/52813779/236949080-c3f7b7a5-707f-4eaf-bd32-d807e3ac31e3.png)

If you know of any conditions or operations, please let me know.

**Comment by amarney4862** [comment]
Might be something specific to my setup then, I'll take a look at it.
