### ISSUE TITLE
lora not found, shows none

### ISSUE THREAD

**Issue by PowerfulShell** [kohya-ss/sd-webui-additional-networks#175]
![image](https://user-images.githubusercontent.com/1768531/236794244-9515206c-4e97-4bb7-81f0-7ac70b53cce8.png)
![image](https://user-images.githubusercontent.com/1768531/236794315-c7406e86-cb29-4666-a0af-a7b9eb2b2fb2.png)
![image](https://user-images.githubusercontent.com/1768531/236795085-f730dee1-6fba-4d9a-a251-2ee9f1ae3d46.png)

**Comment by kohya-ss** [comment]
The issue on the 2nd image has been fixed. I'm not sure about the 1st image, because it cannot be reproduced. But I think it may be caused by the same issue for the 2nd image. If there are any issue, please reopen.

**Comment by PowerfulShell** [comment]
hi, it is because if I don't "specify" the absolute path, to the default lora location, the extension would not find them.....

I get it to work by adding "absolute path"  which i find kinda of annoying cos there is "default lora path" LOL

anyway, thanks for checking in.

OH, what is the difference between JUST using tags<lora:XXX> compares to using this Additional Network extension?
OH, what is the difference between JUST using tags<lora:XXX> compares to using this Additional Network extension?
this is so important, I cannot find answer anywhere on google......

Cheers mate!

**Comment by kohya-ss** [comment]
If the path is relative, it is unclear where the starting point is... 

The built-in LoRA in the Web UI was created to produce the same results as this extension, so the results are basically the same.
This extension supports separate weights for U-Net and Text Encoder, as well as Attention Couple (still a work in progress).

**Comment by PowerfulShell** [comment]
WOW thanks mate! 

also, another good point of this extension is:
it is organized well, like checkpoint drop down menu, 
you know it is far superior than "extra network" cards.... I cannot stand them messy....

thanks for the great plugin

a bit of suggestion, like controlnet you can set how many tabs.... can you make it more than 5 loras? at least we can choose

**Comment by PowerfulShell** [comment]
> If the path is relative, it is unclear where the starting point is...

oh i forgot this, it seems this is same issue like controlnet, it too does not know outside model, unless place inside the extension folder..... i bet this is a gradio issue? anyway, it doesnt really matter now :)

**Comment by PowerfulShell** [comment]
> The built-in LoRA in the Web UI was created to produce the same results as this extension, so the results are basically the same. This extension supports separate weights for U-Net and Text Encoder, as well as Attention Couple (still a work in progress).

after googling a bit of Attention Couple, this is HUGE, hoping to see you pull it off :) I am really excited toward this 

Cheers

**Comment by LanceGao97** [comment]
> e Web UI was created to produce the same results as this extens

where exactly should I put in the folder path,  there are  "" , / and the fucking opsite \ from windows，  I tried more thant 10 combinations,  none of them works,  
suppose my loras are in  StableDifusion/model/loras
,  I  copy         model/loras          save and restart , nothing works,   why is that?

**Comment by LanceGao97** [comment]
I  did all those issues said,   but it still Shows None,    then I solved this fucking problem by myself.
OK，   if you try  relative path    /models/lora  as  everyone says,    resstart,   it shows None
           OK，   if you try  absolut  path    D:programfile ....../models/lora  as      it shows None
that's because you have to click this little brother , cause he does the work, while nobody on this whole thread ever mentioned,
![火狐截图_2023-05-27T10-34-14 894Z](https://github.com/kohya-ss/sd-webui-additional-networks/assets/125782753/5ae79154-a15e-4923-a2db-908b3f964d3d)
