### ISSUE TITLE
LoRA selection bug for remote Gradio users

### ISSUE THREAD

**Issue by seggybop** [kohya-ss/sd-webui-additional-networks#18]
If you're using the Gradio UI from a different machine than the one hosting, the button to select the location of the LoRA will open a file selection dialog box on the host, not on the machine being used. From the user's perspective, it will look like the button isn't working. If you go to the host machine and select the LoRA, it will work, but it can't be set from a client unless they know the file path relative to the host machine and enter it manually.

**Comment by space-nuko** [comment]
Does this still happen since the latest commit? It uses a drop-down instead of a file picker

**Comment by seggybop** [comment]
The update with the drop-down menu fixes it, thank you!
Though, it looks like it requires reloading Gradio to update the list contents if new files are added, so it is bit of a tradeoff.
