### ISSUE TITLE
API request to update the list of LoRAs

### ISSUE THREAD

**Issue by ryankashi** [kohya-ss/sd-webui-additional-networks#184]
Hi!

I noticed that there is no API request available to refresh the list of available LORAs after downloading. For example, with model checkpoints in the webui, there is:

`/sdapi/v1/refresh-checkpoints`, that updates the list for:

`/sdapi/v1/sd-models`,

However for LORAS, there is no equivalent:

`/sdapi/v1/loras`.

In the extension GUI, there is a button to refresh the loras via the button seen in the image below:

![image](https://github.com/kohya-ss/sd-webui-additional-networks/assets/13973467/cc12cb32-5f60-42fe-9f88-791a0f1ac0f6)

Can we add an API path that can call this button programmatically?

**Comment by kohya-ss** [comment]
It appears that the button is not displayed by this extension, but by the built-in LoRA feature of the Web UI.

Please check issues in the Web UI repository.

**Comment by ryankashi** [comment]
Created an open PR on AUTOMATIC1111's stable-diffusion-webui dev branch:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/10529#issue-1716289976
