### ISSUE TITLE
Feature. Store info in generated image metadata

### ISSUE THREAD

**Issue by NeuroNormal** [kohya-ss/sd-webui-additional-networks#19]
Any chance of adding info about used additional networks in image metadata after rendering?
Like add this info:

- Network type (LoRa, etc.)
- Model
- Weight

**Comment by space-nuko** [comment]
The infotext should be implemented in the latest version if you update: https://github.com/kohya-ss/sd-webui-additional-networks/pull/13

**Comment by NeuroNormal** [comment]
> The infotext should be implemented in the latest version if you update: #13

Great! Thanks for info.
