### ISSUE TITLE
[Bug] LoRA Unet only detected as 0 weight even though slider changed to >0

### ISSUE THREAD

**Issue by Linaqruf** [kohya-ss/sd-webui-additional-networks#190]
LoRA only trained the Unet, but it always returns a weight of 0 even though I change the weight slider. Could you please check if it's a bug or not? It works if I turn 'Separate Unet/Tenc weight' to ON. Thank you.

![image](https://github.com/kohya-ss/sd-webui-additional-networks/assets/50163983/09c0f201-e5bb-4949-8ecc-5e0c61c3c327)
![image](https://github.com/kohya-ss/sd-webui-additional-networks/assets/50163983/1477273d-b165-4aff-a6ae-50c9d93f7a97)

**Comment by kohya-ss** [comment]
It seems to be working at my environment. However, the current version of gradio seems to have a problem with the callback of the slider sometimes not working properly. How about moving the slider twice, or input the value directly?

**Comment by kohya-ss** [comment]
The latest commit changed the way slider values are reflected. I think this bug may have been fixed. I would be grateful if you could test it.

**Comment by Linaqruf** [comment]
Thank you so much! I think it has been fixed now 😄

![image](https://github.com/kohya-ss/sd-webui-additional-networks/assets/50163983/97188999-6b79-4ae7-80e0-f5f94bb35629)
![image](https://github.com/kohya-ss/sd-webui-additional-networks/assets/50163983/71a91232-47d1-41dc-a2e5-347b36709a70)

**Comment by kohya-ss** [comment]
That's good! Thank you for testing!
