### ISSUE TITLE
attention coupleブランチの問題

### ISSUE THREAD

**Issue by laksjdjf** [kohya-ss/sd-webui-additional-networks#191]
二つあります。

UNetのみのLoRAしかないと以下のエラーが起こるようです。一つでもテキストエンコーダーを含むLoRAがあれば起こりません。
![タイトルなし-14](https://github.com/kohya-ss/sd-webui-additional-networks/assets/22386664/68b7a1ad-941f-4447-90fa-ffdae7461327)

とりあえず対症療法的に条件式を変えるとうまくいきました。

もう一つはバッチサイズをあげると画像が壊れるようです。
https://github.com/kohya-ss/sd-webui-additional-networks/blob/2605aa9ee7b3dacdd571f55591f69f952e098cab/scripts/additional_networks.py#L482

```cond_list[i] = [(i, 1.0)]```だとうまくいっているようです。

**Comment by kohya-ss** [comment]
報告ありがとうございます。時間でき次第、確認いたします。
