### ISSUE TITLE
1024-network-dim LoRA embeddings are detected as 768-network-dim embeddings

### ISSUE THREAD

**Issue by Fannovel16** [kohya-ss/sd-webui-additional-networks#20]
### Problem
I created some LoRA embeddings with the setting network dim = 1024. When I tested them on your extension, it detected them are having 768 network dim instead of 1024 dim, therefore it skipped almost all the layers in these embeddings due to the mismatch in tensor sizes. I checked the code and found out the bug is at [line 73, lora_compvis.py](https://github.com/kohya-ss/sd-webui-additional-networks/blob/main/scripts/lora_compvis.py#L73). When I changed the value to 1024 manually, it worked. I guess that line can't handle any embedding which has more than 768 network dim.

### Sample files
https://huggingface.co/hr16/Miwano-Rag-LoRA/
I trained these embeddings using [kohya-LoRA-finetuner colab](https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-finetuner.ipynb) by [Linaqruf](https://github.com/Linaqruf/)

**Comment by kohya-ss** [comment]
Indeed, as the number of dimensions increases, the process does not work correctly.

I did not expect LoRA to be used for such a large number of dimensions... I will think about how to handle this.

Perhaps it would be better to specify lora_up or lora_down, and in or out features to get the number of dimensions.

**Comment by Fannovel16** [comment]
This bug is not really noticeable tho as we can get best result with 128 or 256 dimensions.

**Comment by kohya-ss** [comment]
I think this issue is resolved by #51 . If you have any problem, please re-open the issue.
