### ISSUE TITLE
it cannot locate my Lora

### ISSUE THREAD

**Issue by githubUser01946** [kohya-ss/sd-webui-additional-networks#223]
All my Lora's are in the correct place `stable-diffusion-webui\models\Lora` but your extension doesnt find them.

All I am trying to do is find the perfect weight for my Lora.

**Comment by WilliamChen-luckbob** [comment]
I have exactly the same issue after updating my 1111 webui, after updating, all my custom Lora disappeared, and those I downloaded from civitai works fine, I don't know why. My custom Lora was generated by kohya_ss

**Comment by joneschunghk** [comment]
`stable-diffusion-webui\extensions\sd-webui-additional-networks\models\lora`

**Comment by guahunyo** [comment]
> `stable-diffusion-webui\extensions\sd-webui-additional-networks\models\lora`

but i want use  lora in  stable-diffusion-webui\models\Lora  
Is there any way
Otherwise, my lora needs to copy and paste two copies

**Comment by joneschunghk** [comment]
additional network extension only search the lora folder in `\extensions\sd-webui-additional-networks\models\lora`
if you want use lora in `stable-diffusion-webui\models\Lora`, you can use the red-floppy icon under "Generate" botton, and click "Lora" tag. 
As i know, addition network extension doesn't support LoHA and SDXL LoRA.
![20230306-KhveSO 1](https://github.com/kohya-ss/sd-webui-additional-networks/assets/30347563/4497218f-db65-439d-a72e-666eb0a8fb66)
