### ISSUE TITLE
Additional networks not showing in the tab in Forge like in A1111 ?

### ISSUE THREAD

**Issue by MIKETUFFIN66** [kohya-ss/sd-webui-additional-networks#247]
Hello, 
In sd A1111 the Additional networks showing after installation automaticly in the tab above like this :
![2222](https://github.com/user-attachments/assets/3b83a384-8827-4b19-9a8f-a1fe47321437)

in Forge its showing down and dosnt show the lora Meta data like this : 

![001](https://github.com/user-attachments/assets/e8b632bc-9adb-4cc4-bc02-b56142dc243d)

Question : how to enable the Additional networks  to show up in the tabs in Forge UI ? thanks

**Comment by Lumerica** [comment]
if your only concern is about the UI tab additional network at top menu, you can use my fix in #248 

But you should read your console output to find out what is happening tbh.
