### ISSUE TITLE
This extension should respect automatic model swapping settings

### ISSUE THREAD

**Issue by thojmr** [kohya-ss/sd-webui-additional-networks#29]
If the setting `When reading generation parameters from text into UI (from PNG info or pasted text), do not change the selected model/checkpoint.` is enabled, this extension should not clear or replace the current LoRA model when loading an image from PNG Info tab.  This will keep functionality in line with the rest of the webui.

Also the default strength value is 0 now?  So I have to change it manually to 1 every time I load the webui? At least when loading from PNG Info tab it is.

**Comment by kohya-ss** [comment]
Hi, 
I'm not very familiar to development of the extension, I think it is required to check ``shared.opts.disable_weights_auto_swap`` is True or False when ``on_infotext_pasted`` is called. This method seems to work, but if you know this is correct, I would appreciate it if you could let me know.

The default value can be set to 1 when loading. I will change it together.

**Comment by thojmr** [comment]
Yea, that sounds right.  When `shared.opts.disable_weights_auto_swap == True` no LoRA models should be changed or cleared when clicking `Send to txt2img`
