### ISSUE TITLE
[Feature request] multiple extra paths

### ISSUE THREAD

**Issue by ShameSetsu** [kohya-ss/sd-webui-additional-networks#30]
I would like to be able to add multiple extra paths to scan for LoRA models.

index 6bd87ad..6c579c9 100644
--- a/scripts/additional_networks.py
+++ b/scripts/additional_networks.py
@@ -26,9 +26,10 @@ def update_lora_models():
   global lora_models
   res = {}
   paths = [lora_models_dir]
-  extra_lora_path = shared.opts.data.get("additional_networks_extra_lora_path", None)
-  if extra_lora_path and os.path.exists(extra_lora_path):
-    paths.append(extra_lora_path)
+  extra_lora_paths = shared.opts.data.get("additional_networks_extra_lora_path", None)
+  for extra_lora_path in extra_lora_paths.split(","):
+      if extra_lora_paths and os.path.exists(extra_lora_path):
+        paths.append(extra_lora_path)

**Comment by neojam** [comment]
would like to see this feature as well

**Comment by txirrindulari** [comment]
So do I. I keep my models in another drive

**Comment by vivi-gomez** [comment]
Here, you can learn how to add or change extra path https://github.com/kohya-ss/sd-webui-additional-networks/issues/63#issuecomment-1418246032
Thank you

**Comment by neojam** [comment]
Yes, seems like this was already implemented like a week ago. Thank you!
I believe the request can be closed now.
