### ISSUE TITLE
Stuck at [Open "Additional Networks" panel from the left bottom of Web UI]

### ISSUE THREAD

**Issue by StallmanSlave** [kohya-ss/sd-webui-additional-networks#39]
I followed installation instructions, everything appeared to install fine with it displayed in the extensions tab. But I don't see this panel anywhere on the UI.

![help](https://user-images.githubusercontent.com/15690935/212800117-65857690-32b9-4db7-aac0-c482addecfd4.PNG)
![help2](https://user-images.githubusercontent.com/15690935/212800133-a553a8b2-b170-40f6-a61e-f8b62a895f89.PNG)

The extensions I am currently using (if any of them conflicts idk)
![extentions20230117](https://user-images.githubusercontent.com/15690935/212800569-390fa327-83c8-47b0-86a0-e125b0687239.PNG)

**Comment by kohya-ss** [comment]
Hi, 
Please update the web UI to the latest version. If you cant, please download .zip from here:
https://github.com/kohya-ss/sd-webui-additional-networks/releases/tag/v0.1.0

And extract files into the ``extensions/sd-webui-additinal-networks`` to overwrite existing files.

**Comment by StallmanSlave** [comment]
TY the Zip worked. What happens when I need to update it? I have it so the webui batch file pulls Automatic1111's repo to update on start.
