### ISSUE TITLE
[Feature request] Display paths in LoRA-dropdown selection menu

### ISSUE THREAD

**Issue by neojam** [kohya-ss/sd-webui-additional-networks#50]
Hallo,

i would like to have an Option to display relative path in the drop-down menu of LoRAs.
Just the way the Checkpoint-Selection currently works.

This would greatly help with organizing the LoRAs. 
I mostly have each downloaded LoRA in different folder, together with png images that contain embedded promts, readme.txt files and etc.

\Clothes\Traditional Japanese dress\jpdress.safetensors
\Clothes\Negligee\epoch-000004.safetensors
...
\Styles\Katsuhiro Otomo\KatsuhiroEP5safetensors
\Styles\Kentaro Miura\KM.safetensors

**Comment by Nyaster** [comment]
Yes, this is be very coll feature
