### ISSUE TITLE
is there any way this can use the lora folder from the main models folder?

### ISSUE THREAD

**Issue by gsgoldma** [kohya-ss/sd-webui-additional-networks#63]
that way we can load up loras natively or with this extension

**Comment by kohya-ss** [comment]
You can set the main models folder with ``Settings`` tab in the web UI. Select ``Additional Network`` from left bottom, and set the folder to ``Extra path to scan for LoRA models``.

**Comment by Akeyn** [comment]
@gsgoldma If you want to use this folder **"stable-diffusion-webui\models\Lora"** by default, you should set **"Extra paths to scan for LoRA models"** field to **"./models/Lora"**. After that, don't forget to click the **"Refresh models"** button.
![how_to_set_models_folder](https://user-images.githubusercontent.com/26007646/216840632-9f00be02-1120-45a5-a9d8-62d81eab6415.png)
