### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by shirayu** [kohya-ss/sd-webui-additional-networks#76]
It would be nice if you could leave the licence file as you put at https://github.com/kohya-ss/sd-scripts

**Comment by kohya-ss** [comment]
I did the same because WebUI itself does not have a license and other extensions as well, but I agree that the license file will be good. 

I'm not sure it is ok to change the license without confirmation to contributors....

**Comment by shirayu** [comment]
Actually, AGPL was added to the original webui two weeks ago.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/d97f467c0d27695d23edad5e4f8898a57e0ccb00

Although its validity may not be a real issue, it is generally safe to obtain explicit consent from past contributors when deciding on a new licence.
So, I suggest the following steps:


1. decide on a license (assume AGPL in the following steps)
2. put the following content in the ``.github/pull_request_template.md`` file
    ```txt
    ## Description
    
    
    
    ## License agreement
    
    This repository will be licensed under GNU AFFERO GENERAL PUBLIC LICENSE Version 3 (AGPL).
    https://www.gnu.org/licenses/agpl-3.0.en.html
    
    Please leave the following line to indicate your agreement.
    **I agree to license the code contained in this pull request under GNU AFFERO GENERAL PUBLIC LICENSE Version 3.**
    ```
3. get confirmation from [six contributors](https://github.com/kohya-ss/sd-webui-additional-networks/graphs/contributors) on this issue by `@` mentioning them. 
4. If all agree, place the licence file and delete ``.github/pull_request_template.md``

**Comment by kohya-ss** [comment]
Thank you for your kind suggestion! I didn't notice the Web UI has the License now. I've selected ASL 2.0 for ``sd-scripts``, but it will better to select the same license as the Web UI, because this is an extension.

I've added the request template.

**Comment by kohya-ss** [comment]
@space-nuko @shirayu @bmaltais @Fannovel16 @camenduru @ddvarpdd 

Thank you for your contributions! 

AUTOMATIC1111's Web UI has defined the license and I would like to apply the AGPL 3.0 license to this repository as well.
Would you agree to this? I would appreciate your reply to this issue. Thank you very much.

**Comment by shirayu** [comment]
Thanks for the prompt action!
I agree with that. :+1:

**Comment by space-nuko** [comment]
I consent to licensing my past contributions as AGPL 3.0.

**Comment by ddvarpdd** [comment]
Yeah, go ahead.

**Comment by bmaltais** [comment]
100%

**Comment by kohya-ss** [comment]
Thank you to all the contributors!!!
