### ISSUE TITLE
Using LORA weights in X/Y/Z plot in A1111. Is it possible?

### ISSUE THREAD

**Issue by Drakmour** [kohya-ss/sd-webui-additional-networks#83]
Is it possible to put LORA weights to X/Y/Z plot in A1111? Both simple one and 2 that appears if "Separate UNet/Text Encoder weights" is selected. I'd like to have a way to make automatic generations with different weghts.

**Comment by Drakmour** [comment]
Please? Anyone? At least is it possible to add those parameters in the prompt itself? So that I could use a Prompt S/R in X/Y/Z plot. Otherwise, I have to switch the slider and start the generation manually every time to find the best result.

**Comment by Akeyn** [comment]
@Drakmour If you talk about it, then it already exists. Check if you have the latest build of that **[sd-webui-additional-networks]** module and **A1111** 
![xyz_plot](https://user-images.githubusercontent.com/26007646/216842093-193b3213-40cd-44c3-b9f5-deebf50d75e0.png)

**Comment by Drakmour** [comment]
Really? I have a latest build of [sd-webui-additional-networks], I update it every day when I start UI. Maybe a UI updated and added this. I haven't updated the A1111 4-5 last days due to errors and malfunctions after newest updates. I'll try to update and check if i have this too! Thanks!

**Comment by Drakmour** [comment]
> @Drakmour If you talk about it, then it already exists. Check if you have the latest build of that **[sd-webui-additional-networks]

I updated the A1111 and wow it really is there! Very cool. But I don't understand the difference between "AddNet Model" and "AddNet Weight" isn't it the same thing?

**Comment by Akeyn** [comment]
@Drakmour "AddNet Model" - This is a list of models. "AddNet Weight" - This is the power with which to apply it

**Comment by Drakmour** [comment]
> @Drakmour "AddNet Model" - This is a list of models. "AddNet Weight" - This is the power with which to apply it

Oh, so AddNet Model is used to switch between models. Cool. But most loras need trigger words. I can add them in a Additional networks tab in A1111 in Keywords line right? And when I push "save metadata" it will "burn in" those key words and when I choose this lora in X/Y/Z plot it will use this lora with adding those keywords?

**Comment by Akeyn** [comment]
@Drakmour Probably special prompts should be indicated in X/Y/Z plot. But it's better to check.
