### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by EE128** [kohya-ss/sd-webui-additional-networks#89]
Getting this error when trying to use a Lora model trained with the Lora training GUI: https://github.com/bmaltais/kohya_ss

When trying to use the lora model, Automatic1111 gives me:

![image](https://user-images.githubusercontent.com/44074259/216798269-92c001ce-417b-41e3-ad47-e03d6a424dc1.png)

and the model Meta data:

![image](https://user-images.githubusercontent.com/44074259/216798282-939c132d-19a3-4649-9456-a8ac87e03690.png)

The Web Gui is updated, just installed the kohya_ss gui, so I know that's up to date.
All lora model's I've downloaded work perfectly fine, only issues with the one's I'm trying to train.

**Comment by EE128** [comment]
Also, just to see. Reinstalled the additional networks extension. Now getting:

Error running process: C:\Users\herem\OneDrive\Documents\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "C:\Users\herem\OneDrive\Documents\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "C:\Users\herem\OneDrive\Documents\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 206, in process
    network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight_tenc, weight_unet, text_encoder, unet)
TypeError: create_network_and_apply_compvis() takes 4 positional arguments but 5 were given

**Comment by flemingcd** [comment]
I'm receiving the same error. I'm running Automatic1111 in google colab and have uploaded the model (which a friend has shown me works on his local install). @EE128  did you find a solution?

> Error running process: /content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py
> Traceback (most recent call last):
>   File "/content/stable-diffusion-webui/modules/scripts.py", line 338, in process
>     script.process(p, *script_args)
>   File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 177, in process
>     network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight, text_encoder, unet)
>   File "/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py", line 73, in create_network_and_apply_compvis
>     network_dim = min([s for s in size if s > 1])
> ValueError: min() arg is an empty sequence

**Comment by EE128** [comment]
Possibly,
I changed: 
"mem_eff_attn": true,    Was false
 "gradient_checkpointing": true,      Was false
 
 
 
 Those two are the only things I changed and it's been working for me. Fair warning, trains much slower
